"""
Bug Detection Agent

Proactively finds and reports bugs through automated testing,
log analysis, and crash detection.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
import logging
import re
import time

from .base_agent import BaseAutonomousAgent
from .event_bus import Event, EventBus, EventType
from .shared_state import SharedContext

logger = logging.getLogger(__name__)


@dataclass
class Anomaly:
    """
    An anomaly detected in logs or testing.
    
    Attributes:
        anomaly_type: Type of anomaly (error, warning, crash, etc.)
        severity: Severity level
        description: Description of the anomaly
        location: Where it was detected (file, line number, etc.)
        timestamp: When it was detected
        context: Additional context information
    """
    anomaly_type: str
    severity: str
    description: str
    location: str
    timestamp: datetime
    context: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Crash:
    """
    A crash detected during testing or runtime.
    
    Attributes:
        crash_id: Unique identifier for this crash
        timestamp: When the crash occurred
        stack_trace: Stack trace from the crash
        error_message: Error message
        location: Where the crash occurred
        reproducible: Whether the crash is reproducible
    """
    crash_id: str
    timestamp: datetime
    stack_trace: str
    error_message: str
    location: Optional[str] = None
    reproducible: bool = False


@dataclass
class TestResults:
    """
    Results from automated testing.
    
    Attributes:
        test_run_id: Unique ID for this test run
        timestamp: When tests were run
        total_tests: Total number of tests
        passed: Number of tests that passed
        failed: Number of tests that failed
        errors: Number of tests with errors
        duration_seconds: How long tests took
        failures: Details of failed tests
    """
    test_run_id: str
    timestamp: datetime
    total_tests: int
    passed: int
    failed: int
    errors: int
    duration_seconds: float
    failures: List[Dict[str, Any]] = field(default_factory=list)
    
    def success_rate(self) -> float:
        """Calculate test success rate as percentage."""
        if self.total_tests == 0:
            return 0.0
        return (self.passed / self.total_tests) * 100.0


@dataclass
class Regression:
    """
    A regression detected in functionality.
    
    Attributes:
        regression_id: Unique identifier
        timestamp: When detected
        description: Description of the regression
        commit: Commit that introduced the regression (if known)
        previous_behavior: Expected behavior
        current_behavior: Actual behavior
    """
    regression_id: str
    timestamp: datetime
    description: str
    commit: Optional[str] = None
    previous_behavior: str = ""
    current_behavior: str = ""


@dataclass
class BugReport:
    """
    A bug report generated by the agent.
    
    Attributes:
        bug_id: Unique identifier
        title: Short title
        description: Detailed description
        severity: Bug severity
        reproduction_steps: Steps to reproduce
        expected_behavior: Expected behavior
        actual_behavior: Actual behavior
        environment: Environment information
        related_crashes: Related crash reports
        related_anomalies: Related anomalies
    """
    bug_id: str
    title: str
    description: str
    severity: str
    reproduction_steps: List[str]
    expected_behavior: str
    actual_behavior: str
    environment: Dict[str, str] = field(default_factory=dict)
    related_crashes: List[Crash] = field(default_factory=list)
    related_anomalies: List[Anomaly] = field(default_factory=list)


class BugDetectionAgent(BaseAutonomousAgent):
    """
    Agent that proactively detects bugs through testing and monitoring.
    
    Capabilities:
    - Automated testing
    - Log analysis and pattern recognition
    - Crash detection and analysis
    - Regression testing
    - Bug report generation with reproduction steps
    """
    
    def __init__(self,
                 event_bus: EventBus,
                 shared_context: SharedContext,
                 remote_control_client=None):
        """
        Initialize the Bug Detection Agent.
        
        Args:
            event_bus: Event bus for communication
            shared_context: Shared context for coordination
            remote_control_client: Optional UnrealRemoteControlClient for UE integration
        """
        super().__init__(
            agent_id="bug_detection_agent",
            event_bus=event_bus,
            shared_context=shared_context
        )
        
        self._detected_bugs: List[BugReport] = []
        self._detected_crashes: List[Crash] = []
        self._test_history: List[TestResults] = []
        self._max_history_size = 100
        self.remote_control_client = remote_control_client
        self._monitoring_active = False
        
        # Common error patterns
        self._error_patterns = [
            (r'null pointer', 'high'),
            (r'access violation', 'critical'),
            (r'memory leak', 'high'),
            (r'assertion failed', 'high'),
            (r'stack overflow', 'high'),
            (r'infinite loop', 'high'),
        ]
        
        logger.info(f"BugDetectionAgent created (UE integration: {remote_control_client is not None})")
    
    def _subscribe_to_events(self) -> None:
        """Subscribe to relevant events."""
        # Subscribe to test completion events
        self.event_bus.subscribe(EventType.TEST_COMPLETED, self._on_test_completed)
        self.event_bus.subscribe(EventType.TEST_FAILED, self._on_test_failed)
    
    def _unsubscribe_from_events(self) -> None:
        """Unsubscribe from events."""
        self.event_bus.unsubscribe(EventType.TEST_COMPLETED, self._on_test_completed)
        self.event_bus.unsubscribe(EventType.TEST_FAILED, self._on_test_failed)
    
    def _on_start(self) -> None:
        """Initialize bug detection on start."""
        logger.info("Bug detection started")
        self._set_current_task("Monitoring for bugs")
    
    def _on_stop(self) -> None:
        """Clean up on stop."""
        logger.info("Bug detection stopped")
        self._set_current_task(None)
    
    def _on_test_completed(self, event: Event) -> None:
        """Handle test completion event."""
        logger.debug(f"Test completed event received: {event}")
    
    def _on_test_failed(self, event: Event) -> None:
        """Handle test failure event."""
        logger.warning(f"Test failed event received: {event}")
    
    def analyze_logs(self, log_content: str) -> List[Anomaly]:
        """
        Analyze log content for anomalies.
        
        Args:
            log_content: Log file content to analyze
            
        Returns:
            List of detected anomalies
        """
        self._set_current_task("Analyzing logs")
        anomalies = []
        
        # Split into lines
        lines = log_content.split('\n')
        
        for i, line in enumerate(lines):
            # Check for error patterns
            for pattern, severity in self._error_patterns:
                if re.search(pattern, line, re.IGNORECASE):
                    anomalies.append(Anomaly(
                        anomaly_type="error_pattern",
                        severity=severity,
                        description=f"Detected error pattern: {pattern}",
                        location=f"Line {i+1}",
                        timestamp=datetime.now(),
                        context={'line': line.strip()}
                    ))
            
            # Check for error/warning keywords
            line_lower = line.lower()
            if any(keyword in line_lower for keyword in ['error:', 'exception:', '[error]']):
                anomalies.append(Anomaly(
                    anomaly_type="error",
                    severity="high",
                    description="Error message detected in logs",
                    location=f"Line {i+1}",
                    timestamp=datetime.now(),
                    context={'line': line.strip()}
                ))
            elif any(keyword in line_lower for keyword in ['warning:', '[warning]', '[warn]']):
                anomalies.append(Anomaly(
                    anomaly_type="warning",
                    severity="medium",
                    description="Warning message detected in logs",
                    location=f"Line {i+1}",
                    timestamp=datetime.now(),
                    context={'line': line.strip()}
                ))
        
        self._set_current_task(None)
        self._update_metrics(task_completed=True)
        
        logger.info(f"Log analysis completed: {len(anomalies)} anomalies found")
        
        return anomalies
    
    def detect_crashes(self, stack_trace: str, error_message: str) -> Crash:
        """
        Detect and analyze a crash.
        
        Args:
            stack_trace: Stack trace from the crash
            error_message: Error message
            
        Returns:
            Crash object with analysis
        """
        self._set_current_task("Analyzing crash")
        
        # Extract location from stack trace
        location = None
        stack_lines = stack_trace.split('\n')
        if stack_lines:
            # Try to extract file and line from first frame
            match = re.search(r'at (.+?)(?:\s+in\s+(.+?):(\d+))?', stack_lines[0])
            if match:
                location = match.group(1)
        
        crash = Crash(
            crash_id=f"crash_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            timestamp=datetime.now(),
            stack_trace=stack_trace,
            error_message=error_message,
            location=location
        )
        
        # Store crash
        self._detected_crashes.append(crash)
        if len(self._detected_crashes) > self._max_history_size:
            self._detected_crashes.pop(0)
        
        # Publish crash event
        self.event_bus.publish(Event(
            event_type=EventType.CRASH_DETECTED,
            source=self.agent_id,
            payload={
                'crash_id': crash.crash_id,
                'error_message': error_message,
                'location': location
            }
        ))
        
        self._set_current_task(None)
        self._update_metrics(task_completed=True)
        
        logger.error(f"Crash detected: {error_message}")
        
        return crash
    
    def run_automated_tests(self, 
                          test_suite: str,
                          test_count: int = 0,
                          passed: int = 0,
                          failed: int = 0) -> TestResults:
        """
        Run automated tests (simulated for now).
        
        Args:
            test_suite: Name of the test suite
            test_count: Number of tests to run
            passed: Number of passed tests (for simulation)
            failed: Number of failed tests (for simulation)
            
        Returns:
            Test results
        """
        self._set_current_task(f"Running tests: {test_suite}")
        
        start_time = datetime.now()
        
        # In a real implementation, this would actually run tests
        # For now, we create a result object
        results = TestResults(
            test_run_id=f"test_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            timestamp=start_time,
            total_tests=test_count,
            passed=passed,
            failed=failed,
            errors=0,
            duration_seconds=0.0
        )
        
        end_time = datetime.now()
        results.duration_seconds = (end_time - start_time).total_seconds()
        
        # Store results
        self._test_history.append(results)
        if len(self._test_history) > self._max_history_size:
            self._test_history.pop(0)
        
        # Publish test completion event
        event_type = EventType.TEST_FAILED if failed > 0 else EventType.TEST_COMPLETED
        self.event_bus.publish(Event(
            event_type=event_type,
            source=self.agent_id,
            payload={
                'test_run_id': results.test_run_id,
                'test_suite': test_suite,
                'total_tests': test_count,
                'passed': passed,
                'failed': failed,
                'success_rate': results.success_rate()
            }
        ))
        
        self._set_current_task(None)
        self._update_metrics(task_completed=True)
        
        logger.info(f"Tests completed: {passed}/{test_count} passed ({results.success_rate():.1f}%)")
        
        return results
    
    def verify_regressions(self, commit: str) -> List[Regression]:
        """
        Check for regressions after a code change.
        
        Args:
            commit: Commit hash or identifier
            
        Returns:
            List of detected regressions
        """
        self._set_current_task(f"Checking for regressions in {commit}")
        
        # In a real implementation, this would:
        # 1. Run tests before and after the commit
        # 2. Compare results
        # 3. Identify any new failures
        
        regressions = []
        
        # For now, return empty list (placeholder)
        
        self._set_current_task(None)
        self._update_metrics(task_completed=True)
        
        logger.info(f"Regression check completed for {commit}: {len(regressions)} found")
        
        return regressions
    
    def create_bug_report(self,
                         title: str,
                         description: str,
                         severity: str,
                         reproduction_steps: List[str],
                         expected_behavior: str,
                         actual_behavior: str) -> BugReport:
        """
        Create a bug report.
        
        Args:
            title: Bug title
            description: Detailed description
            severity: Severity level
            reproduction_steps: Steps to reproduce
            expected_behavior: Expected behavior
            actual_behavior: Actual behavior
            
        Returns:
            Created bug report
        """
        self._set_current_task("Creating bug report")
        
        bug_report = BugReport(
            bug_id=f"bug_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
            title=title,
            description=description,
            severity=severity,
            reproduction_steps=reproduction_steps,
            expected_behavior=expected_behavior,
            actual_behavior=actual_behavior,
            environment={
                'agent': self.agent_id,
                'timestamp': datetime.now().isoformat()
            }
        )
        
        # Store bug report
        self._detected_bugs.append(bug_report)
        if len(self._detected_bugs) > self._max_history_size:
            self._detected_bugs.pop(0)
        
        # Publish bug detected event
        self.event_bus.publish(Event(
            event_type=EventType.BUG_DETECTED,
            source=self.agent_id,
            payload={
                'bug_id': bug_report.bug_id,
                'title': title,
                'severity': severity,
                'description': description
            }
        ))
        
        self._set_current_task(None)
        self._update_metrics(task_completed=True)
        
        logger.warning(f"Bug report created: {title} (severity: {severity})")
        
        return bug_report
    
    def get_detected_bugs(self, severity: Optional[str] = None) -> List[BugReport]:
        """
        Get detected bugs, optionally filtered by severity.
        
        Args:
            severity: Filter by severity level
            
        Returns:
            List of bug reports
        """
        if severity:
            return [b for b in self._detected_bugs if b.severity == severity]
        return self._detected_bugs.copy()
    
    def get_crash_history(self) -> List[Crash]:
        """Get history of detected crashes."""
        return self._detected_crashes.copy()
    
    def get_test_history(self) -> List[TestResults]:
        """Get history of test runs."""
        return self._test_history.copy()
    
    # ==================== Unreal Engine Integration ====================
    
    def monitor_ue_logs(self, duration_seconds: int = 60) -> List[Anomaly]:
        """
        Monitor Unreal Engine logs in real-time for errors and warnings.
        
        This method continuously monitors the UE editor log output for a specified
        duration, looking for errors, warnings, and other anomalies.
        
        Args:
            duration_seconds: How long to monitor (default: 60 seconds)
            
        Returns:
            List of anomalies detected during monitoring
            
        Raises:
            RuntimeError: If remote_control_client is not configured
        """
        if self.remote_control_client is None:
            logger.error("Cannot monitor UE logs: remote_control_client not configured")
            raise RuntimeError("Remote Control client not configured. Pass it to constructor.")
        
        logger.info(f"Starting UE log monitoring for {duration_seconds} seconds")
        anomalies = []
        start_time = time.time()
        
        try:
            # Start capturing console output
            self.remote_control_client.execute_command("Log LogConsole Display")
            
            while (time.time() - start_time) < duration_seconds:
                # Get recent console output
                response = self.remote_control_client.execute_command("Log List")
                
                if response and 'output' in response:
                    log_content = response['output']
                    
                    # Analyze logs for anomalies
                    new_anomalies = self.analyze_logs(log_content)
                    
                    # Filter out duplicates
                    for anomaly in new_anomalies:
                        if not any(a.description == anomaly.description for a in anomalies):
                            anomalies.append(anomaly)
                            logger.info(f"Detected anomaly: {anomaly.anomaly_type} - {anomaly.description}")
                    
                # Wait before next check
                time.sleep(5)
                
            logger.info(f"UE log monitoring complete. Found {len(anomalies)} anomalies")
            return anomalies
            
        except Exception as e:
            logger.error(f"Error monitoring UE logs: {str(e)}")
            return anomalies
    
    def automated_playtest(self, 
                          duration_seconds: int = 120,
                          test_sequence: Optional[str] = None) -> TestResults:
        """
        Run automated playtest in Unreal Engine and monitor for issues.
        
        This method starts a PIE (Play In Editor) session, optionally runs a test
        sequence, and monitors for errors, crashes, and performance issues.
        
        Args:
            duration_seconds: How long to run the playtest (default: 120 seconds)
            test_sequence: Optional path to a Sequencer asset to execute
            
        Returns:
            TestResults object with test execution details
            
        Raises:
            RuntimeError: If remote_control_client is not configured
        """
        if self.remote_control_client is None:
            logger.error("Cannot run automated playtest: remote_control_client not configured")
            raise RuntimeError("Remote Control client not configured. Pass it to constructor.")
        
        logger.info(f"Starting automated playtest (duration: {duration_seconds}s)")
        test_run_id = f"playtest_{int(time.time())}"
        start_time = time.time()
        errors_found = []
        
        try:
            # Start PIE session
            logger.info("Starting PIE session")
            start_response = self.remote_control_client.execute_command("PIE.StartPlaySession")
            
            if not start_response or not start_response.get('success', False):
                logger.error("Failed to start PIE session")
                return TestResults(
                    test_run_id=test_run_id,
                    timestamp=datetime.now(),
                    total_tests=1,
                    passed=0,
                    failed=1,
                    errors=1,
                    duration_seconds=time.time() - start_time,
                    failures=[{"error": "Failed to start PIE session"}]
                )
            
            # Execute test sequence if provided
            if test_sequence:
                logger.info(f"Executing test sequence: {test_sequence}")
                seq_response = self.remote_control_client.execute_command(
                    f"Sequencer.Play {test_sequence}"
                )
                if not seq_response or not seq_response.get('success', False):
                    errors_found.append({"error": f"Failed to execute sequence: {test_sequence}"})
            
            # Monitor for errors during playtest
            anomalies = []
            while (time.time() - start_time) < duration_seconds:
                # Check for console errors
                response = self.remote_control_client.execute_command("Log List")
                
                if response and 'output' in response:
                    log_content = response['output']
                    new_anomalies = self.analyze_logs(log_content)
                    
                    # Add new unique anomalies
                    for anomaly in new_anomalies:
                        if anomaly.severity in ['high', 'critical']:
                            if not any(a.description == anomaly.description for a in anomalies):
                                anomalies.append(anomaly)
                                errors_found.append({
                                    "type": anomaly.anomaly_type,
                                    "severity": anomaly.severity,
                                    "description": anomaly.description,
                                    "location": anomaly.location
                                })
                
                time.sleep(5)
            
            # Stop PIE session
            logger.info("Stopping PIE session")
            self.remote_control_client.execute_command("PIE.StopPlaySession")
            
            duration = time.time() - start_time
            total_errors = len(errors_found)
            
            # Create test results
            results = TestResults(
                test_run_id=test_run_id,
                timestamp=datetime.now(),
                total_tests=1,
                passed=1 if total_errors == 0 else 0,
                failed=1 if total_errors > 0 else 0,
                errors=total_errors,
                duration_seconds=duration,
                failures=errors_found
            )
            
            # Store in history
            self._test_history.append(results)
            if len(self._test_history) > self._max_history_size:
                self._test_history.pop(0)
            
            # Publish test completed event
            event = Event(
                event_type=EventType.TEST_COMPLETED if results.passed > 0 else EventType.TEST_FAILED,
                source=self.agent_id,
                payload={
                    "test_run_id": test_run_id,
                    "passed": results.passed,
                    "failed": results.failed,
                    "errors": results.errors,
                    "duration": results.duration_seconds
                }
            )
            self.event_bus.publish(event)
            
            logger.info(f"Automated playtest complete: {results.passed} passed, {results.failed} failed")
            return results
            
        except Exception as e:
            logger.error(f"Error during automated playtest: {str(e)}")
            
            # Stop PIE if it's running
            try:
                self.remote_control_client.execute_command("PIE.StopPlaySession")
            except:
                pass
            
            return TestResults(
                test_run_id=test_run_id,
                timestamp=datetime.now(),
                total_tests=1,
                passed=0,
                failed=1,
                errors=1,
                duration_seconds=time.time() - start_time,
                failures=[{"error": str(e)}]
            )
    
    def start_continuous_monitoring(self) -> None:
        """
        Start continuous monitoring of Unreal Engine logs.
        
        This method starts a background monitoring task that continuously watches
        UE logs for errors and warnings. Call stop_continuous_monitoring() to stop.
        
        Raises:
            RuntimeError: If remote_control_client is not configured or monitoring already active
        """
        if self.remote_control_client is None:
            raise RuntimeError("Remote Control client not configured. Pass it to constructor.")
        
        if self._monitoring_active:
            logger.warning("Continuous monitoring already active")
            return
        
        self._monitoring_active = True
        logger.info("Started continuous UE log monitoring")
        
        # Note: In a production implementation, this would start a background thread or task
        # For now, this just sets the flag. The actual monitoring would be done by
        # periodically calling monitor_ue_logs() from an external scheduler.
    
    def stop_continuous_monitoring(self) -> None:
        """Stop continuous monitoring of Unreal Engine logs."""
        self._monitoring_active = False
        logger.info("Stopped continuous UE log monitoring")
    
    def is_monitoring_active(self) -> bool:
        """Check if continuous monitoring is active."""
        return self._monitoring_active
